name: target_teste
description: Teste Target.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
flutter:
  uses-material-design: true
